skip-check:
  - id: CKV_AWS_119
    comment: "Using AWS managed encryption is acceptable for DynamoDB tables"
  - id: CKV_AWS_147
    comment: "Using AWS managed encryption is acceptable for CodeBuild"
  - id: CKV_AWS_116
    comment: "DLQ not required for synchronous IdP authentication flow"
  - id: CKV_AWS_173
    comment: "Using AWS managed encryption is acceptable for Lambda environment variables"
  - id: CKV_AWS_272
    comment: "Code signing adds operational complexity without significant security benefit"
  - id: CKV_AWS_115
    comment: "Concurrent execution limit not required, AWS manages throttling"
