---
fail_fast: false
minimum_pre_commit_version: "2.6.0"
repos:
  - repo: local
    hooks:
      - id: static-tests
        name: static tests
        entry: bash -c 'export BASE_PATH=$(pwd) && export PROJECT_PATH=$(pwd) && ./.project_automation/static_tests/static_tests.sh'
        language: system
        files: \.(tf|md)$
        pass_filenames: false
        require_serial: true