---
fail_fast: false
minimum_pre_commit_version: "2.6.0"
repos:
  - repo: local
    hooks:
      - id: static-tests
        name: static tests
        entry: bash -c 'export PROJECT_PATH=$(pwd) && export PROJECT_TYPE_PATH=$(pwd) && set -x && tail -n +6 ./.project_automation/static_tests/static_tests.sh | bash'
        language: system
        pass_filenames: false
        require_serial: true
        always_run: true
        verbose: true