FROM public.ecr.aws/docker/library/python:3.12-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY agents/individual_agents/database_insertion_agent.py .
ENV AWS_REGION=us-east-1
ENV AWS_DEFAULT_REGION=us-east-1

RUN useradd -m -u 1000 bedrock_agentcore
USER bedrock_agentcore

EXPOSE 8080

CMD ["python", "-m", "database_insertion_agent"]
