version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - yum install -y python3.11 python3.11-pip git
      - python3.11 -m pip install pipenv
      
      - echo "Cloning repository..."
      - git clone --branch $GITHUB_BRANCH --depth 1 $GITHUB_REPO repo
      - cd repo/$SOLUTION_PATH
      
  build:
    commands:
      - echo "Running build script..."
      - chmod +x build.sh
      - ./build.sh
      
      - echo "Installing aws-lambda-powertools in layer..."
      - mkdir -p layer_deps/python
      - cd layer_deps/python
      - python3.11 -m pip install aws-lambda-powertools -t .
      - cd ../..
      
      - echo "Copying existing layer contents..."
      - cp -r src/handler_layer/python/* layer_deps/python/
      
      - echo "Packaging Lambda function..."
      - cd src/idp_handler
      - zip -r ../../function.zip . -x "*.pyc" -x "__pycache__/*"
      - cd ../..
      
      - echo "Packaging Lambda layer with powertools..."
      - cd layer_deps/python
      - zip -r ../../layer.zip . -x "*.pyc" -x "__pycache__/*"
      - cd ../..
      
  post_build:
    commands:
      - echo "Uploading artifacts to S3..."
      - aws s3 cp function.zip s3://$ARTIFACTS_BUCKET/$FUNCTION_ARTIFACT_KEY
      - aws s3 cp layer.zip s3://$ARTIFACTS_BUCKET/$LAYER_ARTIFACT_KEY
      - echo "Build completed successfully"