name: Version Bump

on:
  push:
    branches: [main]

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Get latest commit message
        id: commit
        run: echo "message=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

      - name: Determine version bump type
        id: bump-type
        run: |
          if [[ "${{ steps.commit.outputs.message }}" == *"[Major Release]"* ]]; then
            echo "type=major" >> $GITHUB_OUTPUT
          elif [[ "${{ steps.commit.outputs.message }}" == *"[Minor Release]"* ]]; then
            echo "type=minor" >> $GITHUB_OUTPUT
          else
            echo "type=patch" >> $GITHUB_OUTPUT
          fi

      - name: Bump version
        id: version
        run: |
          if [ ! -f VERSION ]; then
            major=0
            minor=0
            patch=0
          else
            current=$(cat VERSION | sed 's/v//')
            IFS='.' read -r major minor patch <<< "$current"
          fi
          
          case "${{ steps.bump-type.outputs.type }}" in
            major)
              major=$((major + 1))
              minor=0
              patch=0
              ;;
            minor)
              minor=$((minor + 1))
              patch=0
              ;;
            patch)
              patch=$((patch + 1))
              ;;
          esac
          
          new_version="v${major}.${minor}.${patch}"
          echo "$new_version" > VERSION
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Commit version bump
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add VERSION
          git commit -m "Bump version to ${{ steps.version.outputs.new_version }}" || exit 0
          git push
